# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sauce Pipeline Browser Tests

on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - '!docs/**'
      - '!website/**'

env:
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}

jobs:
  puppeteer:
    runs-on: ubuntu-latest
    container:
      image: saucelabs/stt-puppeteer-jest-node:latest
     
    steps:
      # appears that checkout@v2 uses javascript which is not compatible 
      # with the included node version in the container image.
      - name: Checkout Code
        uses: actions/checkout@v1
        
      - name: Workaround for container permissions
        run: sudo chown -R $USER:$(id -gn $USER) /github/home

      - name: Run Sauce Pipeline Test
        run: |
          saucectl run -c ./.sauce/puppeteer.yml
        env:
          BUILD_ID: ${{ github.run_id }}
          BUILD_ENV: GitHub Actions
  playwright:
    runs-on: ubuntu-latest
    container:
      image: saucelabs/stt-playwright-jest-node:latest

    steps:
      # appears that checkout@v2 uses javascript which is not compatible 
      # with the included node version in the container image.
      - name: Checkout Code
        uses: actions/checkout@v1
        
      - name: Workaround for container permissions
        run: sudo chown -R $USER:$(id -gn $USER) /github/home
      
      - name: Workaround for container folder
        run: sudo ln -s /home/seluser/.cache /github/home/.cache

      - name: Run Sauce Pipeline Test
        run: |
          saucectl run -c ./.sauce/playwright.yml
        env:
          BUILD_ID: ${{ github.run_id }}
          BUILD_ENV: GitHub Actions

  testcafe:
    runs-on: ubuntu-latest
    container:
      image: saucelabs/stt-testcafe-node:latest

    steps:
      # appears that checkout@v2 uses javascript which is not compatible 
      # with the included node version in the container image.
      - name: Checkout Code
        uses: actions/checkout@v1
        
      - name: Workaround for container permissions
        run: sudo chown -R $USER:$(id -gn $USER) /github/home
      
      - name: Workaround for container folder
        run: sudo ln -s /home/seluser/.cache /github/home/.cache

      - name: Run Sauce Pipeline Test
        run: |
          saucectl run -c ./.sauce/testcafe.yml
        env:
          BUILD_ID: ${{ github.run_id }}
          BUILD_ENV: GitHub Actions

  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Download saucectl
        run: |
          SAUCECTL_VERSION=0.19.0
          SAUCECTL_BINARY=saucectl_${SAUCECTL_VERSION}_linux_64-bit.tar.gz
          curl -L -o ${SAUCECTL_BINARY} \
              -H "Accept: application/octet-stream" \
              https://github.com/saucelabs/saucectl/releases/download/v${SAUCECTL_VERSION}/${SAUCECTL_BINARY} \
              && tar -xvzf ${SAUCECTL_BINARY}
      - name: Workaround for container permissions
        run: sudo chmod -R 777 tests/
      - name: Run Sauce Pipeline Test
        run: |
          ./saucectl run -c ./.sauce/cypress.yml
        env:
          BUILD_ID: ${{ github.run_id }}
          BUILD_ENV: GitHub Actions

  webdriverio:
    runs-on: ubuntu-latest
    container:
      image: saucelabs/stt-webdriverio-node:latest

    steps:
      # appears that checkout@v2 uses javascript which is not compatible 
      # with the included node version in the container image.
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Workaround for container permissions
        run: sudo chown -R $USER:$(id -gn $USER) /github/home

      - name: Workaround for container folder
        run: sudo ln -s /home/seluser/.cache /github/home/.cache

      - name: Run Sauce Pipeline Test
        run: |
          saucectl run -c ./.sauce/webdriverio.yml
        env:
          BUILD_ID: ${{ github.run_id }}
          BUILD_ENV: GitHub Actions
