apiVersion: v1alpha
kind: testcafe
sauce:
  region: us-west-1
  concurrency: 1 # Controls how many suites are executed at the same time (sauce test env only).
## Tunnel allows you to specify an existing sauce connect tunnel when running testcafe inside the Sauce cloud.
## This has no effect when running tests inside docker.
#  tunnel:
#    id: your_tunnel_id
#    parent: parent_owner_of_tunnel # if applicable, specify the owner of the tunnel
  metadata:
    name: Testing Testcafe Support
    tags:
      - e2e
      - release team
      - other tag
    build: $BUILD_ID
suites:
  - name: "saucy test"
    browserName: "chrome" # Although Testcafe supports triggering one test in multiple browsers, it'd better here to split them into every suite to indicate each suite has its own test point.
    src:
      - "*/*.test.js" # test files glob
    screenshots:
      takeOnFails: true
      fullPage: true
    platformName: "Windows 10"
    env:
      hello: world
    speed: 1

docker:
  # fileTransfer controls how test files are transferred to the docker container before tests are run (choice: mount|copy).
  # `mount` will mount files and folders into the container. Changes to these files and folders will be reflected on the
  # host as well (and vice versa). However, you may run into permission issues depending on your docker or host settings.
  # In this case the usage of `copy` is advised. `copy` will simply copy files and folders into the container.
  fileTransfer: mount # Defaults to `mount`. Choose between mount|copy.
# Docker image and tag are both determined automatically based on your configuration. However, it's possible to set your
# own custom image or a different tag.
  #image: saucelabs/stt-testcafe-node:v0.3.0

testcafe:
  projectPath: tests/testcafe/
  version: 1.11.0
